services:
  webdav:
    image: hacdias/webdav:latest
    container_name: webdav
    expose:
      - "2345/tcp" # Replace with your chosen port.
    networks:
      webdav:
    volumes:
      - ./webdav.yaml:/config.yml:ro # Edit wedav.yaml file before building.
      - ./data:/data
networks:
  webdav:
   external: true
